app = "caw-server"
primary_region = "hkg"

[env]
HOSTNAME = "0.0.0.0"
PORT = 3000
SESSION_MODE = "SESSION"

[build]
dockerfile = "./apps/offercafe-server/Dockerfile"

[http_service]
internal_port = 3000
auto_stop_machines = true
auto_start_machines = true
